version: 2
jobs:
  build:
    docker:
      - image: node:9.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Checks
          command: yarn check-all
