version: 2
jobs:
  build:
    docker:
      - image: node:8.7.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Checks
          command: yarn check-all
  deploy:
    docker:
      - image: node:8.7.0
    steps:
      - checkout
      - run:
          name: Set up auth token
          command: npm set //registry.npmjs.org/:_authToken $AUTH_TOKEN
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Publishes packages
          command: yarn lerna publish --skip-git --canary --yes

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master
